language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

sudo: false

addons:
  apt:
    packages:
      # basics
      - linux-headers-generic
      - build-essential
      # For building things
      - cmake

# "Install" of SMQTK + immediate deps
install:
  # install python dependencies to environment
  - pip install -r requirements.txt

  # Build components of SMQTK
  - mkdir _build
  - pushd _build
  - cmake .. && make
  - popd

  # Environment var export
  - source _build/setup_env.build.sh

# Run tests here
script:
  - sh ./run_tests.sh
